### ISSUE TITLE
[meta] Docs Redesign

### ISSUE THREAD

**Issue by brene** [graphcool/docs#10]
- [ ] Header is wrong on Safari (generally needs redesign) @julianbauer 
- [ ] Header has massive delay during scrolling @brene
- [ ] Distances needs to be adjusted @brene
- [ ] References not responsive @brene
- [ ] Reference navigation should be part of header 
- [ ] Overview of Reference (List) needs to be responsive @brene
- [ ] Guides better responsiveness @julianbauer 
- [ ] new site called Changelog @brene
- [ ] dynamic loading for changelog @brene

**Comment by marktani** [comment]
also see #9
